### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by paulbriton**
In order to finish the work I've started I've made some minor changes: 
  - Correction of vagrant build:
    - Correct an apt-add-repository error
    - Correct an error in the xdebug package
  - Update README.md to include the build status
  - Add an utility function to check presence of an alert box

The last change is required to correct the test suite. I also need a new release of the `2.x` branch for adding this in the phpunit phar (which I would build manually).

After merging these changes, I would finish the correction of the test suite and then open a pull request for the master line. Test suite will be unstable on this branch until the new release.

### CODE REVIEW

**Comment by paulbriton** [comment]
So tests are failing now, but it's ok. They were passing before because of the non-execution of selenium (most of the tests were skipped).
Selenium is running again, and I need fixes above and new release in order to correct the test suite.

**Comment by zerkms** [comment]
So now the dependencies installation is spread across 2 places: the `.ci` scripts and the `.travis.yml`.

How about creating `travis_pre_setup.sh` for consistency with vagrant one?

**Comment by paulbriton** [comment]
Java 8 is a shared dependency between vagrant and travis.
I've first added it to vagrant, and forget to add to Travis, that's why it's spread across those 2 places. I think a better way for consistency is to add java installation in the `setup.sh` script.
I'm testing and pushing this commit to the `2.x` branch.

**Comment by paulbriton** [comment]
Integration of phpunit-selenium in the PHPUnit phar archive is done with ant in the `build.xml` file like this (for 4.8 version): 
```
<exec executable="${basedir}/build/tools/
  <env key="COMPOSER_DISABLE_XDEBUG_WARN" value="1"/>
  <arg value="require"/>
  <arg value="phpunit/phpunit-selenium:~1.4"/>
</exec>
```

The problem is that I need new release of selenium, but for `2.x` branch and I suppose that this release will be `2.0.1` and will not match the composer pattern `~1.4`, so I won't have those changes in the phar.

Should I open an issue or a pull request on PHPUnit in order to change the `build.xml` file or is it possible to release a `1.4.3` version ?

**Comment by giorgiosironi** [comment]
Finally on holiday and have some time for this issue. PHPUnit originally bundled this extension, but it's not going to in the future; I guess 4.8 still does this for its Phar release. The two lines supported for this project are 2.x and 3.x as listed here https://github.com/giorgiosironi/phpunit-selenium/#requirements as 1.x has been dropped due to the dependency on Selenium 1, which nowadays is impossible to use.

So when a PHPUnit branch is still bunding this, it should be updated to require either 2.x or 3.x (since you're talking about PHPUnit 4.8, definitely 2.x).

The goals for this PR to be merged are:
- to make the Vagrant build green using one PHP version (5.6 is the best one)
- to make the Travis CI builds green (uses all 5.x versions supported by the related PHPUnit)

When this is in 2.x, I'll port it to `master` which is where 3.x are released from, using PHP 7 instead.

**Comment by paulbriton** [comment]
@giorgiosironi In order to make the builds green again I first need this PR to be merged. 
I've modified some tests locally and I need the utility function to check presence of an alert box to make the build green again. 
And since phpunit-selenium is included with composer in PHPUnit 4.8, I also need a new release of this project. I would then ask on PHPUnit side to update the version of phpunit-selenium.

Thank's for your time.

**Comment by giorgiosironi** [comment]
Ok, given the current red state it should make no harm. We can then release when it's green, on the `2.x` series.

**Pull request merged**
