### PR TITLE
Fixes #354 waitUtil timeout and sleep interval more configurable

### LINKED ISSUE #354: No way to set sleep interval for waitUntil()
`PHPUnit_Extensions_Selenium2TestCase_WaitUntil` declares `$_defaultSleepInterval` as `private`, and makes it 500ms. But there's no way to override this "default" (it should be called `$_hardcodedSleepInterval`!)

### PR DESCRIPTION
**Pull request by gsouf**
Didn't run the test suit because I dont use vagrant, but travis is a good boy :-)

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Some test related to waitUntil fail, maybe they need to be updated:
https://travis-ci.org/giorgiosironi/phpunit-selenium/jobs/115337340

**Comment by gsouf** [comment]
All my bad, I introduced a typo in ``assertEquals``  Not glorious

**Comment by giorgiosironi** [comment]
Thank you for your contribution. I have added some comments about the style in order to make all APIs consistent with each other (once they are in master they are set in stone) and I will merge after those are dealt with.

**Comment by gsouf** [comment]
About coding standard, that would be a good idea to add a CONTIBUTING.md file, and also some phpcs xml file with the rules, then we can run ``phpcbf``. By the way I will fix these very soon, thanks for the inputs

**Comment by gsouf** [comment]
Sorry for the delay, my contribution interval was not tuned correctly :D

**Comment by giorgiosironi** [comment]
Thanks!

**Pull request merged**
