### PR TITLE
phpunit_7_plus

### LINKED ISSUE #422: PHPUnit 7 supports ?
When is planned supports with PHPUnit 7

### PR DESCRIPTION
**Pull request by thewunder**
Let me know what you think, I wan't able to actually run the mobile tests.

Closes #422

### CODE REVIEW

**Comment by LukeTowers** [comment]
@giorgiosironi what would you need done in order to merge this? We want to use PHPUnit 7+ with OctoberCMS but since we use your library we need your library to support it first.

**Comment by Stepa4man** [comment]
Hey @giorgiosironi, thanks for your lib!
Could you please update me, are you going to merge this PR?
Thanks in advance.

**Comment by sivaschenko** [comment]
Hey @giorgiosironi @thewunder please let me know if I can help with this pull request in any way.

PHPUnit 6 is not supported anymore (https://phpunit.de/supported-versions.html) and it is not compatible with PHP 7.3. So it would be awesome for `phpunit-selenium` to support PHPUnit 7.

**Comment by thewunder** [comment]
@giorgiosironi One last thing is needed to finish this release out is to notify packagist of the new release so it can be made available.  Would that require @sebastianbergmann as he is the maintainer according to packagist?

**Pull request merged**
