### PR TITLE
PHPUnit 9

### PR DESCRIPTION
**Pull request by pajon**
Hi guys, 
there is PHPUnit 9 compatibility.

- Increased PHP version to 7.3
- Tests classes were converted from PSR-0 to PSR-4
- Fixed generation Screenshot path (convert PSR-4 to PSR-0)

I hope we can do more changes before we release the next major version.

### CODE REVIEW

**Review by thewunder — APPROVED** [review]

**Comment by thewunder** [comment]
@pajon Thanks again! I will get a release out shortly

**Comment by dsuurlant** [comment]
What is the progress on creating a `9.0.0` release for this? We'd like to upgrade to PHPUnit 9 but have `phpunit/selenium` as a dependency.

**Comment by thewunder** [comment]
> What is the progress on creating a `9.0.0` release for this?

I quit procrastinating (and imagining I will have spare time to get some other things in) and went ahead and released 9.0!

**Comment by marclaporte** [comment]
And it's now time for PHPUnit 10
https://github.com/giorgiosironi/phpunit-selenium/issues/458

**Pull request merged**
