### PR TITLE
Refactoring tests

### PR DESCRIPTION
**Pull request by carusogabriel**
I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertArrayHasKey` instead of `isset` function;
- `assertInternalType` instead of `is_string` function;
- `assertGreaterThan` for mathematical comparisons.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
The `master` builds seemed to work at https://travis-ci.org/giorgiosironi/phpunit-selenium/branches while this build is failing for unrelated reasons?

**Comment by giorgiosironi** [comment]
Now master fails too, ok.

**Comment by giorgiosironi** [comment]
Opened https://github.com/sebastianbergmann/phpunit/issues/2950 to check why the master test suite started to fail.

**Comment by carusogabriel** [comment]
Ok. I’m out of my home now, but as soon as I return to it, I’ll check the fails!

**Pull request closed without merging**
