### PR TITLE
Fix PHPUnit 6 branch

### PR DESCRIPTION
**Pull request by petrkotek**
My team has finally managed to get PHPUnit 6 w/ Selenium working.

Few more changes in `phpunit_6` were required - see this PR.

Would it be possible to get these changes to the `phpunit_6`?

(Later, it would be nice to get it to `master` and then as a version `4.x`)

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Thank you for this work, I have tried supporting both PHPUnit major versions and failed. The test suite has some problems, but they do not seem related to this changes, any pointer as to what it could be? Are you able to run it locally?

**Comment by petrkotek** [comment]
@giorgiosironi: seems like updating the `geckodriver` and `selenium-server` resolved most of the issues. Now, there is only one issue left:

```
1) Extensions_Selenium2TestCaseTest::testSpecialKeys
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'13,alt'
+'113'
```

Relevant code:
```php
    public function testSpecialKeys()
    {
        $this->url('html/test_special_keys.html');
        $this->byId('input')->click();

        $this->byId('input')->value(Keys::F2);
        $this->assertEquals('113', $this->byId('check')->text());

        $this->byId('input')->value(Keys::ALT . Keys::ENTER);
        $this->assertEquals('13,alt', $this->byId('check')->text());

        $this->byId('input')->value(Keys::CONTROL . Keys::SHIFT . Keys::HOME);
        $this->assertEquals('36,control,shift', $this->byId('check')->text());

        $this->byId('input')->value(Keys::ALT . Keys::SHIFT . Keys::NUMPAD7);
        $this->assertEquals('103,alt,shift', $this->byId('check')->text());
    }
```

Looks like the value of the input doesn't get updating when pressing Alt+ENTER.

**Comment by petrkotek** [comment]
Looks like the key-presses with `Keys::ALT` don't work for some reason. Any ideas?

**Comment by petrkotek** [comment]
@giorgiosironi: do you have any idea what would be a proper way to fix this? looks like `geckodriver`/`selenium-server` changed _something_, but I don't have very deep knowledge of that area.

**Comment by Pierstoval** [comment]
What work has to be done to finish this PR? I have a project I'd like to use this plugin with, and it's incompatible with my current PHPUnit configuration needs 😕

**Comment by petrkotek** [comment]
@Pierstoval: FWIW, I use my branch in a large project and everything works just fine.

(Unfortunately I currently don't have time/motivation to fix these build failures 😢 )

**Comment by Pierstoval** [comment]
@petrkotek What are the incriminated failing builds?

Can we also drop support for HHVM, like Symfony did a few weeks ago for it's future 4.0 branch?

**Comment by giorgiosironi** [comment]
I'll drop HHVM support, merge this into `phpunit_6` and get it into master and a `4.x` release. Sorry for the lack of responses, but I can only work on this project in my free time (if someone is interested in commit rights to help keep the maintenance up, let me know).

**Pull request merged**
