### PR TITLE
Upgrade to PHPUnit 6

### PR DESCRIPTION
**Pull request by pajon**
this is proposal for a new version with PHPUnit 6.0 and PHP 7.*

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Would need to update the `.travis.yml` file to not run the build on PHP 5.6, consistently with the `composer.json`. 

Support for PHPUnit 5 will end in February 2018, so this could not make its way into `master`. It could go into a `4.x` line, but features would have to be ported to both `3.x` and `4.x` for some time. Any chance to make the changes compatible between PHPUnit 5 and PHPUnit 6 to keep a single mainline branch?

**Comment by pajon** [comment]
Hello,
i do some changes but there are compatibility issues (raise errors) with extended classes in PHP 7. There are some solutions with declaring classes in conditions (`if PHP version is >= 7` etc.), but i think it will be better create new branch and version `4.x`.

**Comment by giorgiosironi** [comment]
Due to the namespace changes, it can be too difficult to support both PHPUnit 5.x and 6.x so I agree a `4.x` version is the only solution. Getting this into `phpunit_6` branch.

**Comment by gitlost** [comment]
It might be possible to take the approach used by WordPress in https://core.trac.wordpress.org/ticket/39822 using `class_alias`, see eg https://github.com/gitlost/phpunit-selenium/pull/1.

**Comment by Pierstoval** [comment]
Also agree on releasing a 4.x version for PHPUnit6 and PHP7.

How is this PR doing since April? 😄

**Comment by pajon** [comment]
I have proposed solution but it breaks backwards compatibility with current version (3.x). We can create new version (4.x) and set minimal dependency to PHP 7.0 and PHPUnit 6. This is not the best solution but it's clean way to define dependencies and avoid some bugs.

**Comment by giorgiosironi** [comment]
Have some problems in integration and don't have free time to dedicate to this project unfortunately, so I have to go with https://github.com/giorgiosironi/phpunit-selenium/pull/411 which accomplishes the same goal.

**Pull request merged**
